apiVersion: v1
kind: DeploymentConfig
metadata:
  name: devpi
  labels:
    app: devpi
    component: devpi-server
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 120
      maxUnavailable: 25%
      maxSurge: 25%
    resources:
  triggers:
    - type: ConfigChange
  replicas: 1
  selector:
    app: devpi
    component: devpi-server
  template:
    metadata:
      labels:
        app: devpi
        component: devpi-server
    spec:
      containers:
        - name: devpi
          image: widerin/openshift-devpi:v0.3
          ports:
            - containerPort: 3141
              protocol: TCP
          env:
            - name: DEVPI_MIRROR_CACHE_EXPIRY
              value: '86400'
            - name: DEVPI_PASSWORD
              value: ''
          resources:
            limits:
              cpu: 100m
              memory: 300M
            requests:
              cpu: 100m
              memory: 300M
          volumeMounts:
            - name: devpi-data
              mountPath: /mnt
          livenessProbe:
            tcpSocket:
              port: 3141
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /+status
              port: 3141
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext:
      # Change this if you want to bind a persistent volume claim
      volumes:
        - name: devpi-data
          emptyDir:
